import type { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayoutMain({
  children,
}: Readonly<{ children: React.ReactNode; }>) {
  console.log("RootLayoutMain");
  return (
    <>
      <div>Sou o layout (agrupador) da main</div>
      {children}
    </>
  );
}
