import type { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode; }>) {
  console.log("RootLayout");
  return (
    <html lang="en">
      <body className={`app`}>
        <div>Sou o layout</div>
        {children}
      </body>
    </html>
  );
}
